echo ""
     setup_suspend_hook
     echo ""

     echo -e "${BOLD}========================================${NC}"
     echo -e "${GREEN}Installation complete!${NC}"
     echo ""
     echo "Next steps:"
     echo "  1. Edit configuration:"
     echo -e "     ${BOLD}sudo nano /etc/oshotspot/config.conf${NC}"
     echo ""
     echo "  2. Start the hotspot:"
     echo -e "     ${BOLD}sudo oshotspot start${NC}"
     echo ""
     echo "  3. Check status:"
     echo -e "     ${BOLD}sudo oshotspot status${NC}"
     echo ""
     echo "  4. Show QR code:"
     echo -e "     ${BOLD}sudo oshotspot qr${NC}"
     echo ""
     echo "  5. Stop the hotspot:"
     echo -e "     ${BOLD}sudo oshotspot stop${NC}"
     echo ""
     echo "  6. Repair after suspend:"
     echo -e "     ${BOLD}sudo oshotspot repair${NC}"
     echo ""
     echo "  7. Launch the web dashboard:"
     echo -e "     ${BOLD}sudo oshotspot web${NC}"