#!/usr/bin/env bash
#
# OSHotspot
# Copyright 2026 OLOJEDE Samuel
#
# Licensed under the Apache License, Version 2.0
#
# setup-mail.sh - Configure msmtp for OSHotspot email alerts.
# Generates /etc/oshotspot/msmtprc from user-provided SMTP credentials.

set -euo pipefail

CONFIG_DIR="/etc/oshotspot"
MSMTP_CONF="${CONFIG_DIR}/msmtprc"

if [[ "${EUID}" -ne 0 ]]; then
    echo "[ERROR] This script must be run as root (use sudo)." >&2
    exit 1
fi

if ! command -v msmtp &>/dev/null; then
    echo "[ERROR] msmtp is not installed. Install it first:" >&2
    echo "  sudo apt install msmtp   # Debian/Ubuntu" >&2
    echo "  sudo dnf install msmtp   # Fedora/RHEL" >&2
    exit 1
fi

mkdir -p "${CONFIG_DIR}"

echo ""
echo "========================================="
echo "  OSHotspot Mail Setup (msmtp)"
echo "========================================="
echo ""
echo "Configure msmtp to relay email alerts through an SMTP server."
echo "Press Enter to skip a field and use the default value."
echo ""

# Preset selector
echo "Quick setup presets:"
echo "  1) Gmail (smtp.gmail.com:587)"
echo "  2) Outlook/Hotmail (smtp.office365.com:587)"
echo "  3) Custom SMTP server"
echo ""
read -r -p "Select preset [1-3]: " PRESET

SMTP_HOST=""
SMTP_PORT="587"
USE_TLS="on"

case "${PRESET}" in
    1)
        SMTP_HOST="smtp.gmail.com"
        SMTP_PORT="587"
        echo ""
        echo "For Gmail, you need an App Password (not your regular password):"
        echo "  1. Go to https://myaccount.google.com/apppasswords"
        echo "  2. Create an App Password for 'Mail'"
        echo "  3. Use that 16-character password below"
        echo ""
        ;;
    2)
        SMTP_HOST="smtp.office365.com"
        SMTP_PORT="587"
        echo ""
        echo "For Outlook/Hotmail, use your Microsoft account password."
        echo "Note: You may need to enable 'Less secure app access' or use an App Password."
        echo ""
        ;;
    3)
        read -r -p "SMTP host (e.g. smtp.example.com): " SMTP_HOST
        read -r -p "SMTP port [587]: " INPUT_PORT
        SMTP_PORT="${INPUT_PORT:-587}"
        ;;
    *)
        echo "Invalid selection. Exiting."
        exit 1
        ;;
esac

if [[ -z "${SMTP_HOST}" ]]; then
    echo "[ERROR] SMTP host is required." >&2
    exit 1
fi

read -r -p "SMTP username (email or login): " SMTP_USER
read -r -s -p "SMTP password: " SMTP_PASS
echo ""

if [[ -z "${SMTP_USER}" ]]; then
    echo ""
    echo "[WARN] No username provided. msmtp will connect without authentication."
    echo "       This only works for local/relay servers that don't require auth."
    echo ""
fi

read -r -p "Alert recipient email (where alerts are sent): " ALERT_TO
read -r -p "Alert sender email [oshotspot@localhost]: " ALERT_FROM
ALERT_FROM="${ALERT_FROM:-oshotspot@localhost}"

if [[ -z "${ALERT_TO}" ]]; then
    echo "[ERROR] Recipient email is required." >&2
    exit 1
fi

# Generate msmtp config
cat > "${MSMTP_CONF}" <<MSMTP
# OSHotspot msmtp configuration
# Generated by setup-mail.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Do not edit manually, use 'sudo oshotspot setup-mail' to reconfigure.

# Account settings
account        oshotspot
host           ${SMTP_HOST}
port           ${SMTP_PORT}
from           ${ALERT_FROM}
MSMTP

if [[ -n "${SMTP_USER}" ]]; then
    cat >> "${MSMTP_CONF}" <<MSMTP
auth           on
user           ${SMTP_USER}
password       ${SMTP_PASS}
MSMTP
else
    cat >> "${MSMTP_CONF}" <<MSMTP
auth           off
MSMTP
fi

cat >> "${MSMTP_CONF}" <<MSMTP

# TLS settings
tls            ${USE_TLS}
tls_starttls   on
tls_certcheck  off

# Logging
# logfile       /var/log/oshotspot/msmtp.log

# Set as default account
account default : oshotspot
MSMTP

chmod 600 "${MSMTP_CONF}"
chown root:root "${MSMTP_CONF}"

# Create sendmail symlink so alert.py can find msmtp
MSMTP_BIN="$(command -v msmtp 2>/dev/null || echo "")"
if [[ -n "${MSMTP_BIN}" ]]; then
    if [[ ! -f /usr/sbin/sendmail ]]; then
        ln -sf "${MSMTP_BIN}" /usr/sbin/sendmail
        echo "[OK] Created symlink: /usr/sbin/sendmail -> ${MSMTP_BIN}"
    fi
fi

# Allow msmtp (AppArmor-enforced on Ubuntu) to read our config path.
# Without this rule msmtp fails with EACCES even when run as root.
if command -v aa-status &>/dev/null && aa-status --enabled 2>/dev/null; then
    AA_PROFILE="/etc/apparmor.d/usr.bin.msmtp"
    AA_LOCAL="/etc/apparmor.d/local/usr.bin.msmtp"
    if [[ -f "${AA_PROFILE}" && -f "${AA_LOCAL}" ]]; then
        if ! grep -qF "${MSMTP_CONF}" "${AA_LOCAL}"; then
            {
                echo ""
                echo "# OSHotspot msmtp config location"
                echo "  ${MSMTP_CONF}     r,"
            } >> "${AA_LOCAL}"
            if apparmor_parser -r "${AA_PROFILE}" 2>/dev/null; then
                echo "[OK] AppArmor: msmtp may read ${MSMTP_CONF}"
            else
                echo "[WARN] Added AppArmor rule but failed to reload profile." >&2
                echo "       Run manually: sudo apparmor_parser -r ${AA_PROFILE}" >&2
            fi
        fi
    elif [[ -f "${AA_PROFILE}" ]]; then
        echo "[WARN] AppArmor profile '${AA_PROFILE}' has no local include." >&2
        echo "       If test emails fail with permission errors, add:" >&2
        echo "         ${MSMTP_CONF} r," >&2
        echo "       inside the profile, then reload it with apparmor_parser -r." >&2
    fi
fi

# Update config.conf with email settings
CONFIG_FILE="${CONFIG_DIR}/config.conf"
if [[ -f "${CONFIG_FILE}" ]]; then
    # Remove old ALERT_EMAIL entries and append new ones
    grep -v '^ALERT_EMAIL_' "${CONFIG_FILE}" > "${CONFIG_FILE}.tmp" || true
    cat >> "${CONFIG_FILE}.tmp" <<CONF

# Email alerts via msmtp
ALERT_EMAIL_ENABLED="true"
ALERT_EMAIL_SMTP_MODE="msmtp"
ALERT_EMAIL_TO="${ALERT_TO}"
ALERT_EMAIL_FROM="${ALERT_FROM}"
CONF
    mv "${CONFIG_FILE}.tmp" "${CONFIG_FILE}"
    chmod 600 "${CONFIG_FILE}"
    echo "[OK] Updated ${CONFIG_FILE}"
fi

echo ""
echo "========================================="
echo "  Mail configuration complete!"
echo "========================================="
echo ""
echo "  SMTP host:     ${SMTP_HOST}:${SMTP_PORT}"
echo "  SMTP username: ${SMTP_USER:-<none (no auth)>}"
echo "  Recipient:     ${ALERT_TO}"
echo "  Sender:        ${ALERT_FROM}"
echo "  Config:        ${MSMTP_CONF}"
echo ""
echo "To test, send a test email from the dashboard or run:"
echo "  echo 'Test from OSHotspot' | sudo msmtp --debug -C ${MSMTP_CONF} -a oshotspot ${ALERT_TO}"
echo ""
